// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Control Center Pro contributors

// Bundles the editor into ONE self-contained html file inside CCPUI's
// resources: the panel loads it offline, and `swift build` never needs node.
import { build } from 'esbuild'
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'

const out = '../../Sources/CCPUI/Resources/NoteWebEditor'
const result = await build({
  entryPoints: ['src/main.js'], bundle: true, minify: true, format: 'iife',
  target: 'safari18', write: false, legalComments: 'none',
})
const js = result.outputFiles[0].text.replaceAll('</script', '<\\/script')
const css = readFileSync('src/editor.css', 'utf8')
mkdirSync(out, { recursive: true })
writeFileSync(`${out}/editor.html`, `<!-- SPDX-License-Identifier: GPL-3.0-or-later. Generated by Spikes/tiptap-editor/build.mjs; Tiptap and ProseMirror are MIT. -->
<!doctype html><html><head><meta charset="utf-8"><style>${css}</style></head>
<body><div id="editor"></div><script>${js}</script></body></html>
`)
console.log(`editor.html: ${(js.length / 1024).toFixed(0)} KB js`)
